### ISSUE TITLE
Can not build project after add plugin bottomsheet

### ISSUE THREAD

**Issue by minhson95th** [nativescript-community/ui-persistent-bottomsheet#1]
after i add plugin `ns plugin add @nativescript-community/ui-persistent-bottomsheet`, i run `tns run android` and it show error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> Could not resolve all task dependencies for configuration ':releaseCompileClasspath'.
   > Could not find :widgets-release:.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s
Failed to build plugin @nativescript-community/gesturehandler : 
Error: Command gradlew.bat failed with exit code 1
```

**Comment by farfromrefug** [comment]
the error seems to be related to gesturehandler. but I don't have a enough info.to.help you. need more logs

**Comment by minhson95th** [comment]
> the error seems to be related to gesturehandler. but I don't have a enough info.to.help you. need more logs

how can i get logs for you?

**Comment by farfromrefug** [comment]
just give me more than the part you printed here. it is missing the actual error

**Comment by minhson95th** [comment]
please update demo-ng folder because now it's sample of ui-drawer, not ui-persistent-bottomsheet

**Comment by farfromrefug** [comment]
@minhson95th sorry but i dont that much time to do that right now. Either use the vue demo or you are welcome to create a PR.
