### ISSUE TITLE
Prevent background taps

### ISSUE THREAD

**Issue by guillemc23** [nativescript-community/ui-persistent-bottomsheet#12]
When the bottomsheet is expanded, I believe the most logical behavior is to prevent taps on the background

### Which platform(s) does your issue occur on?
- Android 
- Android 12
- Xiaomi Redmi Note 9

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.4.0
- Cross-platform modules: 8.4.8
- Runtime(s): 8.3.0
- Plugin(s): 0.0.22

### Please, tell us how to recreate the issue in as much detail as possible. 
If there's a button on the background and the bottomsheet is covering it, it can still be tapped

**Comment by farfromrefug** [comment]
@guillemc23 not with this plugin. It is exactly what it does not want to do :D 
Maybe you are more looking or @nativescript-community/ui-material-bottomsheet which is "modal"

**Comment by guillemc23** [comment]
Hmmm I think this is the plugin I want/need. I'm just a bit confused by this behavior.

I made the following demo video to explain it better. I feel like the red button shouldn't be tappable when it's *behind* the expanded bottomsheet, but the green should be as well as the scrollview since the bottomsheet is not convering them.

https://www.veed.io/view/f601b42c-ba91-47a6-a427-51d42b5edae2?sharingWidget=true&panel=share

**Comment by farfromrefug** [comment]
This plugin is made to work like google maps bottom sheet for selected map business. The idea is to be able to interact with the map while showing the bottom sheet.
Same qwith Spotify /tidal play bar

**Comment by guillemc23** [comment]
Yes, I understand that. Interacting with the map showing in the background that can be seen on top of the bottomsheet is the desired behavior.

Did you get the chance to look at the video I posted? Tapping a button that is covered by the bottomsheet does not happen when using Google Maps.

**Comment by farfromrefug** [comment]
@guillemc23 sorry your video does not work here. It remains a 0:00

**Comment by guillemc23** [comment]
Let me try YouTube this time 😅 

https://youtube.com/shorts/kUCwKw9290c?feature=share

**Comment by farfromrefug** [comment]
@guillemc23 ok i see now. It is not a plugin issue per say, more a N issue/behavior.If layout as not tap attached it is passthrough....
The simple fix is to add an empty tap event on the green layout.
